CREATE TABLE carrinho
(
    carrinho_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id  BIGINT                                  NOT NULL,
    valor_total DECIMAL,
    CONSTRAINT pk_carrinho PRIMARY KEY (carrinho_id)
);

ALTER TABLE carrinho
    ADD CONSTRAINT uc_carrinho_usuario UNIQUE (usuario_id);

ALTER TABLE carrinho
    ADD CONSTRAINT FK_CARRINHO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id);