CREATE TABLE produtos
(
    produto_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome       VARCHAR(255),
    preco      DECIMAL,
    descricao  VARCHAR(255),
    categoria  VARCHAR(255),
    CONSTRAINT pk_produtos PRIMARY KEY (produto_id)
);