CREATE TABLE pedido
(
    pedido_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status_pedido VARCHAR(255)                            NOT NULL,
    usuario_id    BIGINT                                  NOT NULL,
    valor_total   DECIMAL,
    CONSTRAINT pk_pedido PRIMARY KEY (pedido_id)
);

CREATE TABLE pedido_produto
(
    pedido_id  BIGINT NOT NULL,
    produto_id BIGINT NOT NULL
);

ALTER TABLE pedido
    ADD CONSTRAINT FK_PEDIDO_ON_USUARIO FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id);

ALTER TABLE pedido_produto
    ADD CONSTRAINT fk_pedpro_on_item_carrinho FOREIGN KEY (produto_id) REFERENCES item_carrinho (item_carrinho_id);

ALTER TABLE pedido_produto
    ADD CONSTRAINT fk_pedpro_on_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (pedido_id);